
logging-config-path: logging.yaml

search-terms:
  - alex

search-results:
  offset: 0
  page-size: 10
  page-count: 1

storage-path: files

out-file-templ: ids_map_{0}.json

pictures-dir: pic

picture-format: jpg

picture-size: [70, 70]

processed-pic-dir: pic_proc

overwrite-existing: False

access-token: EAACEdEose0cBAOaS8fixjKzK70lO9J1o8akZAnSZBSsSW0ZAlmZABShX9g7X29n8O6ZAaUV1OmZCwo3iriuN5iLe8KjnkyV0k7ANp4hZBf9iXd3rJnjalnZCJga8aOSPXApf4uMTqz4G1AsWgW7uOzZAZBZBkoQ1I4ZBsrrYJSOFn7mw5PI9J2waijyaV2Tp4ieZCxImzLgaDOzuv2wZDZD

model-path: ../faces/models/pca_svc_2.pkl