
logging-config-path: logging.yaml

search-terms:
  - alex
  - kate

search-results:
  offset: 0
  page-size: 2
  page-count: 1

storage-path: files

out-file-templ: ids_map_{0}.json

pictures-dir: pic

picture-format: jpg

picture-size: [100, 100]

processed-pic-dir: pic_proc

overwrite-existing: False

access-token: EAACEdEose0cBAKBptDNh2AMV7A0pHtYLDP9UCZBIZCnbyklephYPL6kXBJmhjpojqVyg9XMdXs8umWRUzNF3XlMGPMH6dYssXkk4DoUpF5uvWe0jhXoE0Qk8tmzQbkRmcYd5YZB7vlxSO7tpYgiQAOLq0QIOtTZBFET8ArTgfZCXP50coBcrSBDrGv9kaVd0ZD