
logging-config-path: logging.yaml

search-terms:
  - alex
  # - kate
  # - jack
  # - sofia
  # - david
  # - lucy
  # - mike
  # - nina
  # - joseph
  # - tom

search-results:
  offset: 100
  page-size: 10
  page-count: 1

storage-path: files

out-file-templ: ids_map_{0}.json

pictures-dir: pic

picture-format: jpg

picture-size: [100, 100]

processed-pic-dir: pic_proc

overwrite-existing: False

access-token: EAACEdEose0cBANuFzGf1q0tfptpaMCmmNtrxOZAJGrqD6MBBoums7dMcpkqZB0R2qGZCny6eBX6QTgAVOyLLyFcQMH6A7ZBq1iUokayCfZB3tQfpQE2vC5rn4tkClCgpwJN1PQ8lOG1xECnG3mUkNgYNl47PVfpvZAx8nBMi5ChP8CCyB5agrPZAvIGadU3rsoZD